#include "appGPIO.h"
//	#include "config.h"
#include "gpio.h"

void GPIO_init()
{
	core_GPIO_init(EN1A_PORT, EN1A_PIN, GPIO_MODE_INPUT, GPIO_PULLUP);
	core_GPIO_init(EN1B_PORT, EN1B_PIN, GPIO_MODE_INPUT, GPIO_PULLUP);
	core_GPIO_init(PBEN1_PORT, PBEN1_PIN, GPIO_MODE_INPUT, GPIO_PULLUP);

	core_GPIO_init(EN2A_PORT, EN2A_PIN, GPIO_MODE_INPUT, GPIO_PULLUP);
	core_GPIO_init(EN2B_PORT, EN2B_PIN, GPIO_MODE_INPUT, GPIO_PULLUP);
	core_GPIO_init(PBEN2_PORT, PBEN2_PIN, GPIO_MODE_INPUT, GPIO_PULLUP);

	core_GPIO_init(EN3A_PORT, EN3A_PIN, GPIO_MODE_INPUT, GPIO_PULLUP);
	core_GPIO_init(EN3B_PORT, EN3B_PIN, GPIO_MODE_INPUT, GPIO_PULLUP);
	core_GPIO_init(PBEN3_PORT, PBEN3_PIN, GPIO_MODE_INPUT, GPIO_PULLUP);

	core_GPIO_init(PB1_PORT, PB1_PIN, GPIO_MODE_INPUT, GPIO_PULLUP);
	core_GPIO_init(PTT_PORT, PTT_PIN, GPIO_MODE_INPUT, GPIO_PULLUP);

	core_GPIO_init(LED1_PORT, LED1_PIN, GPIO_MODE_OUTPUT_PP, GPIO_PULLDOWN);
	core_GPIO_init(LED2_PORT, LED2_PIN, GPIO_MODE_OUTPUT_PP, GPIO_PULLDOWN);

	core_GPIO_digital_write(LED1_PORT, LED1_PIN, false);
	core_GPIO_digital_write(LED2_PORT, LED2_PIN, false);
}

